//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/CarMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/CarMovement.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CarMovement: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CarMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""CarMovement"",
    ""maps"": [
        {
            ""name"": ""PlayerActionMap_"",
            ""id"": ""c0ef4e9f-9684-4b60-b5ff-72ab98e22ed6"",
            ""actions"": [
                {
                    ""name"": ""OnMove"",
                    ""type"": ""Value"",
                    ""id"": ""881645b7-32cf-47b7-9d02-ebb7d65d9534"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnPause"",
                    ""type"": ""Button"",
                    ""id"": ""c1ec8dca-29a2-403d-bc6f-f965befd8810"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnRestartScene"",
                    ""type"": ""Button"",
                    ""id"": ""6a5bf7f0-ee2f-4865-b4ca-1a65ab678641"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnMoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""11b786ea-df42-4a2d-8f86-5cce83666aea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD Move"",
                    ""id"": ""ba7629f4-ce88-44be-86b2-8af4b3e75667"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5ecad884-3da1-4dd7-82a6-3dc8ba25998e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1896854c-96b3-42b7-ade8-e4b1e9430fa7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""951e8162-ad34-4658-a11e-8c4c88d07eee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ae3507d-b42c-4b4a-b3d5-0526671c9d0e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Move"",
                    ""id"": ""84c06110-b726-4d9c-9e2a-f44f024bc49f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""38751589-22bf-47d7-9075-9db380fa960c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""eaaa5360-ecd6-453a-b683-b854349f71aa"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""044100fb-ff78-40fb-b9dd-99419de8a88e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93f55b12-cbb7-4565-8d18-d7474a1d16e7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""65f1a7a9-8481-41f0-b7ee-ea0f96b47be3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1464fd7-f398-4e11-b691-dc3bc1cbb0b6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a577c81d-8f43-40f6-a9de-65fff370577a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnRestartScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a24ca66-a0d7-49d9-bb06-495cb60ce4dd"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActionMap_
        m_PlayerActionMap_ = asset.FindActionMap("PlayerActionMap_", throwIfNotFound: true);
        m_PlayerActionMap__OnMove = m_PlayerActionMap_.FindAction("OnMove", throwIfNotFound: true);
        m_PlayerActionMap__OnPause = m_PlayerActionMap_.FindAction("OnPause", throwIfNotFound: true);
        m_PlayerActionMap__OnRestartScene = m_PlayerActionMap_.FindAction("OnRestartScene", throwIfNotFound: true);
        m_PlayerActionMap__OnMoveCamera = m_PlayerActionMap_.FindAction("OnMoveCamera", throwIfNotFound: true);
    }

    ~@CarMovement()
    {
        UnityEngine.Debug.Assert(!m_PlayerActionMap_.enabled, "This will cause a leak and performance issues, CarMovement.PlayerActionMap_.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActionMap_
    private readonly InputActionMap m_PlayerActionMap_;
    private List<IPlayerActionMap_Actions> m_PlayerActionMap_ActionsCallbackInterfaces = new List<IPlayerActionMap_Actions>();
    private readonly InputAction m_PlayerActionMap__OnMove;
    private readonly InputAction m_PlayerActionMap__OnPause;
    private readonly InputAction m_PlayerActionMap__OnRestartScene;
    private readonly InputAction m_PlayerActionMap__OnMoveCamera;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerActionMap_".
    /// </summary>
    public struct PlayerActionMap_Actions
    {
        private @CarMovement m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActionMap_Actions(@CarMovement wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerActionMap_/OnMove".
        /// </summary>
        public InputAction @OnMove => m_Wrapper.m_PlayerActionMap__OnMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActionMap_/OnPause".
        /// </summary>
        public InputAction @OnPause => m_Wrapper.m_PlayerActionMap__OnPause;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActionMap_/OnRestartScene".
        /// </summary>
        public InputAction @OnRestartScene => m_Wrapper.m_PlayerActionMap__OnRestartScene;
        /// <summary>
        /// Provides access to the underlying input action "PlayerActionMap_/OnMoveCamera".
        /// </summary>
        public InputAction @OnMoveCamera => m_Wrapper.m_PlayerActionMap__OnMoveCamera;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionMap_; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActionMap_Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActionMap_Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActionMap_Actions" />
        public void AddCallbacks(IPlayerActionMap_Actions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionMap_ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionMap_ActionsCallbackInterfaces.Add(instance);
            @OnMove.started += instance.OnOnMove;
            @OnMove.performed += instance.OnOnMove;
            @OnMove.canceled += instance.OnOnMove;
            @OnPause.started += instance.OnOnPause;
            @OnPause.performed += instance.OnOnPause;
            @OnPause.canceled += instance.OnOnPause;
            @OnRestartScene.started += instance.OnOnRestartScene;
            @OnRestartScene.performed += instance.OnOnRestartScene;
            @OnRestartScene.canceled += instance.OnOnRestartScene;
            @OnMoveCamera.started += instance.OnOnMoveCamera;
            @OnMoveCamera.performed += instance.OnOnMoveCamera;
            @OnMoveCamera.canceled += instance.OnOnMoveCamera;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActionMap_Actions" />
        private void UnregisterCallbacks(IPlayerActionMap_Actions instance)
        {
            @OnMove.started -= instance.OnOnMove;
            @OnMove.performed -= instance.OnOnMove;
            @OnMove.canceled -= instance.OnOnMove;
            @OnPause.started -= instance.OnOnPause;
            @OnPause.performed -= instance.OnOnPause;
            @OnPause.canceled -= instance.OnOnPause;
            @OnRestartScene.started -= instance.OnOnRestartScene;
            @OnRestartScene.performed -= instance.OnOnRestartScene;
            @OnRestartScene.canceled -= instance.OnOnRestartScene;
            @OnMoveCamera.started -= instance.OnOnMoveCamera;
            @OnMoveCamera.performed -= instance.OnOnMoveCamera;
            @OnMoveCamera.canceled -= instance.OnOnMoveCamera;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActionMap_Actions.UnregisterCallbacks(IPlayerActionMap_Actions)" />.
        /// </summary>
        /// <seealso cref="PlayerActionMap_Actions.UnregisterCallbacks(IPlayerActionMap_Actions)" />
        public void RemoveCallbacks(IPlayerActionMap_Actions instance)
        {
            if (m_Wrapper.m_PlayerActionMap_ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActionMap_Actions.AddCallbacks(IPlayerActionMap_Actions)" />
        /// <seealso cref="PlayerActionMap_Actions.RemoveCallbacks(IPlayerActionMap_Actions)" />
        /// <seealso cref="PlayerActionMap_Actions.UnregisterCallbacks(IPlayerActionMap_Actions)" />
        public void SetCallbacks(IPlayerActionMap_Actions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionMap_ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionMap_ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActionMap_Actions" /> instance referencing this action map.
    /// </summary>
    public PlayerActionMap_Actions @PlayerActionMap_ => new PlayerActionMap_Actions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerActionMap_" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActionMap_Actions.AddCallbacks(IPlayerActionMap_Actions)" />
    /// <seealso cref="PlayerActionMap_Actions.RemoveCallbacks(IPlayerActionMap_Actions)" />
    public interface IPlayerActionMap_Actions
    {
        /// <summary>
        /// Method invoked when associated input action "OnMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnPause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnRestartScene" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnRestartScene(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnMoveCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnMoveCamera(InputAction.CallbackContext context);
    }
}
